winzou_state_machine:
    sylius_order:
        class: "%sylius.model.order.class%"
        property_path: state
        graph: sylius_order
        state_machine_class: "%sylius.state_machine.class%"
        states:
            cart: ~
            new: ~
            cancelled: ~
            fulfilled: ~
            accepted: ~
            refused: ~
            ready: ~
        transitions:
            create:
                from: [cart]
                to: new
            cancel:
                from: [new, accepted]
                to: cancelled
            fulfill:
                from: [accepted, ready]
                to: fulfilled
            accept:
                from: [new]
                to: accepted
            refuse:
                from: [new]
                to: refused
            ready:
                from: [accepted]
                to: ready
    sylius_payment:
        class: AppBundle\Entity\StripePayment
        property_path: state
        graph: sylius_payment
        state_machine_class: "%sylius.state_machine.class%"
        states:
            cart: ~
            new: ~
            authorized: ~
            processing: ~
            completed: ~
            failed: ~
            cancelled: ~
            void: ~
            refunded: ~
            refunded_partially: ~
        transitions:
            create:
                from: [cart]
                to: new
            authorize:
                from: [cart, new]
                to: authorized
            process:
                from: [new]
                to: processing
            complete:
                from: [new, authorized, processing]
                to: completed
            fail:
                from: [cart, new, authorized]
                to: failed
            cancel:
                from: [cart, new, authorized]
                to: cancelled
            refund:
                from: [completed, refunded_partially]
                to: refunded
            refund_partially:
                from: [completed]
                to: refunded_partially
            void:
                from: [new, processing]
                to: void
    task:
        class: AppBundle\Entity\Task
        property_path: status
        graph: task
        state_machine_class: "%sylius.state_machine.class%"
        states:
            TODO: ~
            DONE: ~
            FAILED: ~
            CANCELLED: ~
        transitions:
            markAsDone:
                from: [TODO]
                to: DONE
            markAsFailed:
                from: [TODO]
                to: FAILED
            cancel:
                from: [TODO]
                to: CANCELLED
