AppBundle\Entity\Address:
    type: entity
    table: address
    indexes:
        idx_address_geo:
            columns:
                - geo
            flags:
                - spatial
    options:
        spatial_indexes:
            - idx_address_geo
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        description:
            type: text
            nullable: true
        floor:
            type: string
            nullable: true
        geo:
            type: geography
            options:
                geometry_type: GEOMETRY
                srid: 4326
            requireSQLConversion: true
        addressCountry:
            type: string
            nullable: true
            column: address_country
        addressLocality:
            type: string
            column: address_locality
            nullable: true
        addressRegion:
            type: string
            nullable: true
            column: address_region
        postalCode:
            type: string
            column: postal_code
            nullable: true
        postOfficeBoxNumber:
            type: string
            nullable: true
            column: post_office_box_number
        streetAddress:
            type: string
            column: street_address
        firstName:
            type: string
            nullable: true
            column: first_name
        lastName:
            type: string
            nullable: true
            column: last_name
        company:
            type: string
            nullable: true
            column: company
        telephone:
            type: phone_number
            nullable: true
        contactName:
            type: string
            nullable: true
            column: contact_name
