AppBundle\Entity\ApiApp:
    type: entity
    table: api_app
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
        createdAt:
            type: datetime
            column: created_at
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            column: updated_at
            gedmo:
                timestampable:
                    on: update
    manyToOne:
        oauth2Client:
            targetEntity: Trikoder\Bundle\OAuth2Bundle\Model\Client
            cascade:
                - persist
            joinColumns:
                oauth2_client_id:
                    referencedColumnName: identifier
                    nullable: false
        store:
            targetEntity: AppBundle\Entity\Store
            joinColumns:
                store_id:
                    referencedColumnName: id
                    nullable: false
