AppBundle\Entity\Bot:
    type: entity
    table: bot
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        lastPosition:
            type: geography
            column: last_position
            nullable: true
            options:
                geometry_type: GEOMETRY
                srid: 4326
            requireSQLConversion: true
        createdAt:
            type: datetime
            column: created_at
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            column: updated_at
            gedmo:
                timestampable:
                    on: update
    oneToOne:
        user:
            targetEntity: AppBundle\Entity\ApiUser
            joinColumns:
                user_id:
                    referencedColumnName: id
                    nullable: false
