AppBundle\Entity\Delivery\Package:
    type: entity
    table: delivery_package
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        quantity:
            type: integer
    manyToOne:
        delivery:
            targetEntity: AppBundle\Entity\Delivery
            inversedBy: packages
            joinColumns:
                delivery_id:
                    referencedColumnName: id
                    nullable: false
        package:
            targetEntity: AppBundle\Entity\Package
            joinColumns:
                package_id:
                    referencedColumnName: id
                    nullable: false


