AppBundle\Entity\Delivery\PricingRule:
    type: entity
    table: pricing_rule
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        expression:
            type: text
        price:
            type: text
        position:
            type: integer
            nullable: true
    manyToOne:
        ruleSet:
            targetEntity: AppBundle\Entity\Delivery\PricingRuleSet
            cascade:
                - persist
            fetch: LAZY
            inversedBy: rules
            joinColumns:
                rule_set_id:
                    referencedColumnName: id
                    nullable: false
