AppBundle\Entity\Package:
    type: entity
    table: package
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
        volumeUnits:
            type: integer
            column: volume_units
        createdAt:
            type: datetime
            column: created_at
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            column: updated_at
            gedmo:
                timestampable:
                    on: update
    manyToOne:
        packageSet:
            targetEntity: AppBundle\Entity\PackageSet
            inversedBy: packages
            joinColumns:
                package_set_id:
                    referencedColumnName: id
                    onDelete: 'SET NULL'
