AppBundle\Entity\PackageSet:
    type: entity
    table: package_set
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
        createdAt:
            type: datetime
            column: created_at
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            column: updated_at
            gedmo:
                timestampable:
                    on: update
    oneToMany:
        packages:
            targetEntity: AppBundle\Entity\Package
            cascade:
                - all
            mappedBy: packageSet
            orphanRemoval: true
