AppBundle\Entity\RemotePushToken:
    type: entity
    table: remote_push_token
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        platform:
            type: string
        token:
            type: string
        createdAt:
            type: datetime
            column: created_at
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            column: updated_at
            gedmo:
                timestampable:
                    on: update
    manyToOne:
        user:
            targetEntity: AppBundle\Entity\ApiUser
            inversedBy: remotePushTokens
            joinColumns:
                user_id:
                    referencedColumnName: id
                    nullable: false
