AppBundle\Entity\Restaurant\PreparationTimeRule:
    type: entity
    table: restaurant_preparation_time_rule
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        expression:
            type: text
        position:
            type: integer
            gedmo:
                - sortablePosition
        time:
            type: string
    manyToOne:
        restaurant:
            targetEntity: AppBundle\Entity\Restaurant
            inversedBy: preparationTimeRules
            joinColumns:
                restaurant_id:
                    referencedColumnName: id
                    onDelete: SET NULL
            gedmo:
                - sortableGroup
