AppBundle\Entity\Restaurant\PledgeVote:
    type: entity
    table: restaurant_pledge_vote
    uniqueConstraints:
        restaurant_pledge_vote_user_unique:
            columns:
                - pledge_id
                - user_id
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        votedAt:
            type: datetime
            column: voted_at
            gedmo:
                timestampable:
                    on: create
    manyToOne:
        pledge:
            targetEntity: AppBundle\Entity\Restaurant\Pledge
            inversedBy: votes
            cascade:
                - all
            joinColumns:
                pledge_id:
                    referencedColumnName: id
            # orphanRemoval: false
        user:
            targetEntity: AppBundle\Entity\ApiUser
            joinColumns:
                user_id:
                    referencedColumnName: id
                    nullable: false
