AppBundle\Entity\Restaurant\Pledge:
    type: entity
    table: restaurant_pledge
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
        state:
            type: string
        createdAt:
            type: datetime
            column: created_at
            gedmo:
                timestampable:
                    on: create
    oneToOne:
        address:
            targetEntity: AppBundle\Entity\Address
            cascade:
                - all
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                address_id:
                    referencedColumnName: id
            orphanRemoval: false
        restaurant:
            targetEntity: AppBundle\Entity\Restaurant
            cascade:
                - all
            fetch: LAZY
            mappedBy: null
            inversedBy: pledge
            joinColumns:
                restaurant_id:
                    referencedColumnName: id
            orphanRemoval: false
    manyToOne:
        user:
            targetEntity: AppBundle\Entity\ApiUser
            joinColumns:
                user_id:
                    referencedColumnName: id
                    nullable: false
    oneToMany:
        votes:
            targetEntity: AppBundle\Entity\Restaurant\PledgeVote
            cascade:
                - all
            mappedBy: pledge
            # joinColumns:
            #     pledge_id:
            #         referencedColumnName: id
            #         nullable: false

