AppBundle\Entity\StripePayment:
    type: entity
    table: stripe_payment
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        currencyCode:
            type: string
            length: 3
            column: currency_code
        amount:
            type: integer
        state:
            type: string
        details:
            type: json_array
        createdAt:
            type: datetime
            column: created_at
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            column: updated_at
            gedmo:
                timestampable:
                    on: update
    manyToOne:
        order:
            targetEntity: Sylius\Component\Order\Model\OrderInterface
            inversedBy: payments
            fetch: LAZY
            joinColumns:
                order_id:
                    referencedColumnName: id
                    nullable: false
                    onDelete: CASCADE
