AppBundle\Entity\StripeAccount:
    type: entity
    table: stripe_account
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        type:
            type: string
        displayName:
            type: string
            column: display_name
        payoutsEnabled:
            type: boolean
            column: payouts_enabled
            default: false
        stripeUserId:
            type: string
            column: stripe_user_id
        refreshToken:
            type: string
            column: refresh_token
        livemode:
            type: boolean
            default: false
        createdAt:
            type: datetime
            column: created_at
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            column: updated_at
            gedmo:
                timestampable:
                    on: update
