AppBundle\Entity\Sylius\ProductOption:
    type: entity
    table: sylius_product_option
    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: false
            hard_delete: false
    fields:
        strategy:
            type: string
            options:
                default: 'free'
        price:
            type: integer
            nullable: true
        additional:
            type: boolean
        deletedAt:
            type: datetime
            nullable: true
        valuesRange:
            type: numrange
            nullable: true
