AppBundle\Entity\Sylius\Taxon:
    type: entity
    table: sylius_taxon
    oneToMany:
        taxonProducts:
            targetEntity: AppBundle\Entity\Sylius\ProductTaxon
            mappedBy: taxon
            cascade:
                - all
            orderBy:
                position: ASC
