AppBundle\Entity\Sylius\OrderReceiptLineItem:
    type: entity
    table: sylius_order_receipt_line_item
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    manyToOne:
        parent:
            targetEntity: AppBundle\Entity\Sylius\OrderReceipt
            inversedBy: lineItems

