AppBundle\Entity\Sylius\OrderEvent:
    type: entity
    table: sylius_order_event
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        type:
            type: string
        data:
            type: json_array
        metadata:
            type: json_array
        createdAt:
            type: datetime
            column: created_at
    manyToOne:
        order:
            targetEntity: Sylius\Component\Order\Model\OrderInterface
            inversedBy: events
            joinColumns:
                aggregate_id:
                    referencedColumnName: id
