AppBundle\Entity\Sylius\FrozenOrderFooterItem:
    type: mappedSuperclass
    fields:
        name:
            type: string
        total:
            type: integer
        position:
            type: integer
            gedmo:
                - sortablePosition
