AppBundle\Entity\Sylius\ProductOptions:
    type: entity
    table: sylius_product_options
    uniqueConstraints:
        sylius_product_option_unique:
            columns:
                - product_id
                - option_id
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        position:
            type: integer
            gedmo:
                - sortablePosition
    manyToOne:
        product:
            targetEntity: Sylius\Component\Product\Model\ProductInterface
            inversedBy: options
            joinColumns:
                product_id:
                    referencedColumnName: id
                    nullable: false
            gedmo:
                - sortableGroup
        option:
            targetEntity: Sylius\Component\Product\Model\ProductOptionInterface
            joinColumns:
                option_id:
                    referencedColumnName: id
                    nullable: false
