AppBundle\Entity\Sylius\ProductVariantOptionValue:
    type: entity
    table: sylius_product_variant_option_value
    uniqueConstraints:
        sylius_product_variant_option_value_unique:
            columns:
                - variant_id
                - option_value_id
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        quantity:
            type: integer
    manyToOne:
        variant:
            targetEntity: Sylius\Component\Product\Model\ProductVariantInterface
            joinColumns:
                variant_id:
                    referencedColumnName: id
                    nullable: false
        optionValue:
            targetEntity: Sylius\Component\Product\Model\ProductOptionValueInterface
            joinColumns:
                option_value_id:
                    referencedColumnName: id
                    nullable: false
