AppBundle\Entity\Sylius\OrderTimeline:
    type: entity
    table: sylius_order_timeline
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        createdAt:
            type: datetime
            column: created_at
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            column: updated_at
            gedmo:
                timestampable:
                    on: update
        dropoffExpectedAt:
            type: datetime
            column: dropoff_expected_at
            nullable: false
        pickupExpectedAt:
            type: datetime
            column: pickup_expected_at
            nullable: false
        preparationExpectedAt:
            type: datetime
            column: preparation_expected_at
            nullable: false
    oneToOne:
        order:
            targetEntity: Sylius\Component\Order\Model\OrderInterface
            inversedBy: timeline
            joinColumns:
                order_id:
                    referencedColumnName: id
