AppBundle\Entity\Sylius\OrderReceipt:
    type: entity
    table: sylius_order_receipt
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    oneToMany:
        lineItems:
            targetEntity: AppBundle\Entity\Sylius\OrderReceiptLineItem
            mappedBy: parent
            cascade:
                - all
        footerItems:
            targetEntity: AppBundle\Entity\Sylius\OrderReceiptFooterItem
            mappedBy: parent
            cascade:
                - all
    oneToOne:
        order:
            targetEntity: Sylius\Component\Order\Model\OrderInterface
            inversedBy: receipt
            joinColumn:
                order_id:
                    referencedColumnName: id
            cascade:
                - persist
                - remove
