AppBundle\Entity\Sylius\OrderReceiptFooterItem:
    type: entity
    table: sylius_order_receipt_footer_item
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    manyToOne:
        parent:
            targetEntity: AppBundle\Entity\Sylius\OrderReceipt
            inversedBy: footerItems
            gedmo:
                - sortableGroup

