AppBundle\Entity\Sylius\FrozenOrderLineItem:
    type: mappedSuperclass
    fields:
        name:
            type: string
        description:
            type: text
            nullable: true
        quantity:
            type: integer
        unitPrice:
            type: integer
            column: unit_price
        subtotal:
            type: integer
        taxTotal:
            type: integer
            column: tax_total
        total:
            type: integer
