AppBundle\Entity\Sylius\ProductTaxon:
    type: entity
    table: sylius_product_taxon
    uniqueConstraints:
        sylius_product_taxon_unique:
            columns:
                - product_id
                - taxon_id
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        position:
            type: integer
            gedmo:
                - sortablePosition
    manyToOne:
        product:
            targetEntity: Sylius\Component\Product\Model\ProductInterface
            joinColumns:
                product_id:
                    referencedColumnName: id
                    nullable: false
                    onDelete: CASCADE
        taxon:
            targetEntity: Sylius\Component\Taxonomy\Model\TaxonInterface
            inversedBy: taxonProducts
            orphanRemoval: true
            joinColumns:
                taxon_id:
                    referencedColumnName: id
                    nullable: false
                    onDelete: CASCADE
            gedmo:
                - sortableGroup
