AppBundle\Entity\Tagging:
    type: entity
    table: tagging
    uniqueConstraints:
        tagging_unique:
            columns:
                - resource_class
                - resource_id
                - tag_id
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        resourceClass:
            type: string
            column: resource_class
        resourceId:
            type: integer
            column: resource_id
    manyToOne:
        tag:
            targetEntity: AppBundle\Entity\Tag
            fetch: LAZY
            joinColumns:
                tag_id:
                    referencedColumnName: id
                    nullable: false
