AppBundle\Entity\TaskImage:
    type: entity
    table: task_image
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        imageName:
            type: string
            column: image_name
            length: 255
        createdAt:
            type: datetime
            column: created_at
            gedmo:
                timestampable:
                    on: create
    manyToOne:
        task:
            targetEntity: AppBundle\Entity\Task
            inversedBy: images
            joinColumns:
                task_id:
                    referencedColumnName: id
