AppBundle\Entity\TaskEvent:
    type: entity
    table: task_event
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
        data:
            type: json_array
        metadata:
            type: json_array
        createdAt:
            type: datetime
            column: created_at
    manyToOne:
        task:
            targetEntity: AppBundle\Entity\Task
            fetch: LAZY
            inversedBy: events
            joinColumns:
                task_id:
                    referencedColumnName: id
                    nullable: false
