AppBundle\Entity\TaskList:
    type: entity
    table: task_list
    repositoryClass: AppBundle\Entity\TaskListRepository
    uniqueConstraints:
        task_list_unique:
            columns:
                - date
                - courier_id
    fields:
        date:
            type: date
    manyToOne:
        courier:
            targetEntity: AppBundle\Entity\ApiUser
            fetch: LAZY
            joinColumns:
                courier_id:
                    referencedColumnName: id
                    nullable: false
