AppBundle\Entity\TimeSlot\Choice:
    type: entity
    table: time_slot_choice
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        startTime:
            type: string
            column: start_time
        endTime:
            type: string
            column: end_time
        createdAt:
            type: datetime
            column: created_at
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            column: updated_at
            gedmo:
                timestampable:
                    on: update
    manyToOne:
        timeSlot:
            targetEntity: AppBundle\Entity\TimeSlot
            joinColumns:
                time_slot_id:
                    referencedColumnName: id
                    nullable: true
