services:

  _defaults:
    autowire: true
    autoconfigure: true

  misd_phone_number.serializer.normalizer:
    class: AppBundle\Serializer\PhoneNumberNormalizer
    arguments:
      - '@libphonenumber.phone_number_util'
      - '%country_iso%'

  AppBundle\Serializer\DeliveryNormalizer:
    arguments:
      $normalizer: '@api_platform.jsonld.normalizer.item'
    tags: [ { name: serializer.normalizer, priority: 128 } ]

  AppBundle\Serializer\RestaurantNormalizer:
    arguments:
      - "@api_platform.jsonld.normalizer.item"
      - "@router"
      - '@request_stack'
      - "@vich_uploader.templating.helper.uploader_helper"
      - "@sylius.context.currency"
      - "@coopcycle.price_formatter"
      - "@slugify"
      - "%kernel.default_locale%"
    tags: [ { name: serializer.normalizer, priority: 128 } ]

  AppBundle\Serializer\TaskNormalizer:
    arguments:
      $normalizer: '@api_platform.jsonld.normalizer.item'
    tags: [ { name: serializer.normalizer, priority: 128 } ]

  AppBundle\Serializer\TaskListNormalizer:
    arguments:
      - "@api_platform.jsonld.normalizer.item"
    tags: [ { name: serializer.normalizer, priority: 128 } ]

  AppBundle\Serializer\TaskImageNormalizer:
    arguments:
      $normalizer: '@api_platform.jsonld.normalizer.item'
    tags: [ { name: serializer.normalizer, priority: 128 } ]

  AppBundle\Serializer\ClosingRuleNormalizer:
    arguments:
      - "@api_platform.jsonld.normalizer.item"
    tags: [ { name: serializer.normalizer, priority: 128 } ]

  AppBundle\Serializer\JsonLd\OrderNormalizer:
    arguments:
      $normalizer: "@api_platform.jsonld.normalizer.item"
      $objectNormalizer: "@serializer.normalizer.object"
      $productOptionValueRepository: "@sylius.repository.product_option_value"
      $variantResolver: "@coopcycle.sylius.product_variant_resolver.lazy"
      $orderItemFactory: "@sylius.factory.order_item"
    tags: [ { name: serializer.normalizer, priority: 128 } ]

  AppBundle\Serializer\Json\OrderItemNormalizer:
    arguments:
      - "@serializer.normalizer.object"
    tags: [ { name: serializer.normalizer, priority: 128 } ]

  AppBundle\Serializer\JsonLd\RestaurantMenuNormalizer:
    arguments:
      - "@api_platform.jsonld.normalizer.item"
      - "@sylius.locale_provider"
      - "@sylius.product_variant_resolver.default"
    tags: [ { name: serializer.normalizer, priority: 128 } ]
