services:

  _defaults:
    autowire: true
    autoconfigure: true

  AppBundle\Twig\:
    resource: '../../../src/AppBundle/Twig/*'

  League\Flysystem\Filesystem $assetsFilesystem: '@assets_filesystem'

  AppBundle\Twig\AppearanceRuntime:
    arguments:
      $logoFallback: '%kernel.project_dir%/web/img/logo.png'

  AppBundle\Twig\TaxRateRuntime:
    arguments:
      $taxRateRepository: '@sylius.repository.tax_rate'

  Twig_Extensions_Extension_Text:
    class: Twig_Extensions_Extension_Text
    tags:
      - { name: twig.extension }

  Twig_Extensions_Extension_Intl:
    class: Twig_Extensions_Extension_Intl
    tags:
      - { name: twig.extension }
